name: Metrics
on:
  schedule: # Schedule updates (e.g. daily)
    - cron: '0 0 * * *'
  workflow_dispatch: # Manual trigger
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
